### ISSUE TITLE
Maximum depth?

### ISSUE THREAD

**Issue by bschollnick** [benhoyt/scandir#20]
Ben

What about adding a maximum depth?  It would be nice to be able to say only go two levels deep, when dealing with recursion.

**Comment by dotsdl** [comment]
Any thoughts on re-opening this? Working on [a package](https://github.com/datreant/datreant.core) that relies heavily on `scandir`'s speed, but since there's no way to tell the `scandir.walk` iterator how far to go, the only choice appears to be `continue`ing the loop whenever the depth is too far. This of course is still really slow since the whole tree gets walked anyway.

**Comment by benhoyt** [comment]
@dotsdl Unfortunately this isn't really within the scope of scandir -- `scandir()` itself is a low-level, non-recursive function, and then `walk()` is just a reimplementation of Python's `os.walk()` (no new features) using scandir instead of listdir.

The most straight-forward way to get what you want is to reimplement the subset of `walk()` that you need using scandir, and add a `depth` parameter to limit the recursion depth.

You could also use the existing `scandir.walk()` an modify the *dirnames* list in place -- i.e., clear out the dir names when the root is more than N levels deep. See more in the `os.walk()` docs here: https://docs.python.org/2/library/os.html#os.walk

Hope that helps!

**Comment by dotsdl** [comment]
Ah, gotcha. Thanks for the tips! I see a way forward now on my issue.
