### ISSUE TITLE
Does not build on Windows with python 2.7

### ISSUE THREAD

**Issue by raboof** [benhoyt/scandir#64]
Installing scandir on windows 8 (64-bit) with python 2.7 (32-bit) fails with:
![selection_116](https://cloud.githubusercontent.com/assets/131856/18005339/b38c1b08-6b99-11e6-84e2-d8a890fcc3e4.png)
Keywords: VOLUME_NAME_DOS, FSCTL_GET_REPARSE_POINT undeclared

I'm using 32-bits python because winrandom (https://pypi.python.org/pypi/winrandom/1.2) is only packaged for 32-bits, and the gcc-for-windows package I found (https://github.com/develersrl/gccwinbinaries) is not available for 64-bits python (https://github.com/develersrl/gccwinbinaries/issues/2)

**Comment by benhoyt** [comment]
Hmmm, that's interesting. However, I don't think Python supports gcc/mingw on Windows, only Microsoft Visual C++. You can get a free version specifically to compile Python 2.7, see here: https://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/

**Comment by raboof** [comment]
Aha! I'm new to running Python on Windows, so please bear with me here a bit :).

I actually did find and install http://aka.ms/vcpython27, but winrandom seemed to request gcc specifically. As winrandom is already packaged for 32-bits python, though, I don't actually need it anymore right now.

After uninstalling https://github.com/develersrl/gccwinbinaries scandir could be successfully installed! Thanks for the pointer!

**Comment by benhoyt** [comment]
Good to hear!

**Comment by kxrob** [comment]
Same problem here - and I prefer gcc.

Note: Python (2.7) distutils support gcc/mingw officially as well - when its present only, or explicitely by a config line in distutils.cfg .  See: http://stackoverflow.com/questions/3297254/how-to-use-mingws-gcc-compiler-when-installing-python-package-using-pip

Most extensions compile with MingW - one and the same MingW for different python versions! Thats a standard also. Thus, you don't need to host a dozen of weired VC's  (unless you are an official binary provider or so).

2 simple suggestions, to make it compileable in a good manner everywhere: 
* The 2 missing constants VOLUME_NAME_DOS and FSCTL_GET_REPARSE_POINT  are in <winbase.h> and <winioctl.h> , which should be explicitely #include'd by _scandir.c (or winrepars.h). That would be more clear with VC usage also.
* do the strange redefinition of "typedef struct _REPARSE_DATA_BUFFER ... REPARSE_DATA_BUFFER, *PREPARSE_DATA_BUFFER"  (which must be somewhere in the VC includes also!?) only if the stuff is not already defined - by using #ifndef ...

**Comment by kxrob** [comment]
And: Linking fails on Win XP because GetFinalPathNameByHandleW  is only on >=Win Vista. Would be fine if XP compatibility could be maintained by using another approach. 

Note: GetFinalPathNameByHandle  doesn't work for zero length files and directories anyway.  
Here a compatible and more robust function:
http://stackoverflow.com/questions/65170/how-to-get-name-associated-with-open-handle

But strange also: win32_xstat_impl_w  uses CreateFile ; and  /* In order to call GetFinalPathNameByHandle we need to **open  the file** without the reparse handling flag set. */

=> Why not simply stay with  GetFileAttributesEx etc like Pythons os.stat / .lstat  implementations which don't open the files !? Not all files can be opened.
